import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { AddTodo, Footer } from '../components';

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Nextjs-todo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className={styles.container}>
          <h2 className={styles.title}>Todo</h2>
          <div className={styles.wrapper}>
            <div className={styles.todoContainer}>
              <div className={styles.header} />
              <AddTodo />
              <div className={styles.list}>
                todoContainer
              </div>
            </div>
          </div>
          <Footer />
        </div>
      </main>
    </>
  );
};

export default Home;
